name: build-macos

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  mac-build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build mac DMG
        run: npm run build:mac

      - name: Upload dmg only
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: dist/*.dmg


